import Footer from "./components/Footer/Footer";
import Header from "./components/Header/Header";
import { Noto_Sans_Mono } from "next/font/google";
const font = Noto_Sans_Mono({
  weight: ["200", "400", "700"],
  subsets: ["latin"],
});
import "./globals.scss";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${font.className}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
